media: src/assets/images
content:
- name: blog
  label: Blog
  path: src/content/blog
  type: collection
  fields:
  - name: title
    label: Title
    type: string
    required: true
  - name: description
    label: Description
    type: string
    required: true
  - name: pubDate
    label: Publication Date
    type: date
  - name: category
    label: Category
    type: string
    required: true
  - name: heroImage
    label: Hero Image
    type: image
    required: true
    options:
      path: src/assets/images
      extensions: [jpg, jpeg, png]
  - name: tags
    label: Tags
    type: string
    list: true
    required: true
  - name: body
    label: Body
    type: rich-text
    required: true
    options:
      image:
        path: src/assets/images
        extensions: [jpg, jpeg, png]
  