name: CI
on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Cache Nix derivations
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: actions/checkout@v2
      - name: Fetch all git history
        run: git fetch --force --prune --tags --unshallow
      - name: Build website
        run: nix build
